INSERT INTO Carta(nome_stand, imagem) VALUES("The Fool", "/View/Modules/JoJo_Tarot/Images/Cards/00.jpg"),
("Magician's Red", "/View/Modules/JoJo_Tarot/Images/Cards/01.jpg"),
("High Priestess", "/View/Modules/JoJo_Tarot/Images/Cards/02.jpg"),
("Empress", "/View/Modules/JoJo_Tarot/Images/Cards/03.jpg"),
("Emperor", "/View/Modules/JoJo_Tarot/Images/Cards/04.jpg"),
("Hierophant Green", "/View/Modules/JoJo_Tarot/Images/Cards/05.jpg"),
("Lovers", "/View/Modules/JoJo_Tarot/Images/Cards/06.jpg"),
("Silver Chariot", "/View/Modules/JoJo_Tarot/Images/Cards/07.jpg"),
("Strength", "/View/Modules/JoJo_Tarot/Images/Cards/08.jpg"),
("Hermit Purple", "/View/Modules/JoJo_Tarot/Images/Cards/09.jpg"),
("Wheel of Fortune", "/View/Modules/JoJo_Tarot/Images/Cards/10.jpg"),
("Justice", "/View/Modules/JoJo_Tarot/Images/Cards/11.jpg"),
("Hanged Man", "/View/Modules/JoJo_Tarot/Images/Cards/12.jpg"),
("Death Thirteen", "/View/Modules/JoJo_Tarot/Images/Cards/13.jpg"),
("Yellow Temperance", "/View/Modules/JoJo_Tarot/Images/Cards/14.jpg"),
("Ebony Devil", "/View/Modules/JoJo_Tarot/Images/Cards/15.jpg"),
("Tower of Gray", "/View/Modules/JoJo_Tarot/Images/Cards/16.jpg"),
("Star Platinum", "/View/Modules/JoJo_Tarot/Images/Cards/17.jpg"),
("Dark Blue Moon", "/View/Modules/JoJo_Tarot/Images/Cards/18.jpg"),
("Sun", "/View/Modules/JoJo_Tarot/Images/Cards/19.jpg"),
("Judgement", "/View/Modules/JoJo_Tarot/Images/Cards/20.jpg"),
("The World", "/View/Modules/JoJo_Tarot/Images/Cards/21.jpg");